# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/111iR-aHHSDbZXLMXHgciRbviJ4pWP97a

HackerRank Task 3 Python:
Arithmetic Operators:

Take 2 inputs a and b 
Add code to print three lines where:

*   The first line contains the sum of the two numbers.
*   The second line contains the difference of the two numbers (first - second).

*   The third line contains the product of the two numbers
"""

a=int(input())
b=int(input())

print(a+b)
print(a-b)
print(a*b)