# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/111iR-aHHSDbZXLMXHgciRbviJ4pWP97a

HackerRank Task 1 Python:
Print Hello World
"""

print("Hello, World!")

#another way of printing a string 

my_string="Hello, World!"
print(my_string)